export {default as Register} from "./Register/Register"
export {default as Creditos} from "./Creditos/Creditos"
export {default as Home} from "./Home/Home"
export {default as Login} from "./Login/Login"
export {default as MeusAgendamentos} from "./Meus Agendamentos/MeusAgendamentos"
export {default as NovoAgendamento} from "./Novo Agendamento/NovoAgendamento"